name: Promote dev → main (auto)

on:
  push:
    branches: [ dev ]

# Wichtig: globale Permissions setzen,
# damit der eingebaute GITHUB_TOKEN genug Rechte hat
permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    uses: Strompreise-Schweiz/supplier-data-validation/.github/workflows/validate_supplier.yml@main
    with:
      supplier_schema_version: v1

  promote:
    needs: validate
    if: ${{ needs.validate.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update PR dev → main
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: dev
          title: "Promote dev → main (auto)"
          body: "Automatisch erstellt nach erfolgreichem Validation-Run."
      
      - name: Enable auto-merge (squash)
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
