name: Promote dev → main (auto)

on:
  push:
    branches: [ dev ]

jobs:
  validate:
    uses: Strompreise-Schweiz/supplier-data-validation/.github/workflows/validate_supplier.yml@main
    with:
      supplier_schema_version: v1

  promote:
    needs: validate
    if: ${{ needs.validate.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # PR dev → main erstellen oder holen (mit PAT!)
      - name: Create or fetch PR
        id: pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}   # PAT statt GITHUB_TOKEN
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = 'main';
            const head = `${owner}:dev`;

            // Offene PRs head=dev → base=main suchen
            const { data: list } = await github.rest.pulls.list({ owner, repo, state: 'open', base, head });
            let pr = list[0];

            // Falls keiner existiert: neu erstellen
            if (!pr) {
              const created = await github.rest.pulls.create({
                owner, repo, base, head: 'dev',
                title: 'Promote dev → main (auto)',
                body: 'Automatisch erstellt nach erfolgreichem Validation-Run.'
              });
              pr = created.data;
            }

            core.setOutput('number', pr.number);

      # Auto-merge aktivieren (respektiert Branch-Protection)
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}         # PAT!
          pull-request-number: ${{ steps.pr.outputs.number }}
          merge-method: squash
