name: Promote dev → main (auto)

on:
  push:
    branches: [ dev ]

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    uses: Strompreise-Schweiz/supplier-data-validation/.github/workflows/validate_supplier.yml@main
    with:
      supplier_schema_version: v1
