name: Validate (supplier & logo)
on: [push, pull_request]

jobs:
  call:
    uses: Strompreise-Schweiz/supplier-data-validation/.github/workflows/validate_supplier.yml@main
    with:
      supplier_schema_version: v1
