name: Promote dev → main (auto)

on:
  push:
    branches: [ dev ]

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    uses: Strompreise-Schweiz/supplier-data-validation/.github/workflows/validate_supplier.yml@main
    with:
      supplier_schema_version: v1

  promote:
    needs: validate
    if: ${{ needs.validate.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create or fetch PR dev → main
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // offenen PR dev -> main suchen
            const prs = await github.paginate(
              github.rest.pulls.list,
              { owner, repo, state: 'open', base: 'main', head: `${owner}:dev` }
            );

            let pr = prs[0];
            if (!pr) {
              const created = await github.rest.pulls.create({
                owner, repo,
                head: 'dev',
                base: 'main',
                title: 'Promote dev → main (auto)',
                body: 'Automatisch erstellt nach erfolgreichem Validation-Run.'
              });
              pr = created.data;
            }

            core.setOutput('number', String(pr.number));

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.pr.outputs.number }}
          merge-method: squash
